"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------
# Basic Security Settings
# ------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-my)k8-n3icz%j5ju=oy=qy+l(rs$_q)0cr2tfy6r^dj@(f8whm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Must be False in production

# Add your domain(s) for production
ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']


# ------------------------------
# Application definition
# ------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'users',
]

AUTH_USER_MODEL = 'users.CustomUser'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ------------------------------
# Middleware
# ------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "relationship_app.security_middleware.SecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# ------------------------------
# Database
# ------------------------------
# Using SQLite for development; replace with production DB as needed
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------------------
# Password Validation
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ------------------------------
# Internationalization
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ------------------------------
# Static files
# ------------------------------
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------
# Security Enhancements
# ------------------------------

# Browser security
SECURE_BROWSER_XSS_FILTER = True          # Enable browser XSS filter
X_FRAME_OPTIONS = 'DENY'                  # Prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True        # Prevent MIME type sniffing

# Cookies security
CSRF_COOKIE_SECURE = True                 # Only send CSRF cookie over HTTPS
SESSION_COOKIE_SECURE = True              # Only send session cookie over HTTPS

# HTTPS / SSL settings
SECURE_SSL_REDIRECT = True                # Redirect all HTTP requests to HTTPS
SECURE_HSTS_SECONDS = 31536000            # HSTS: 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True     # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True                # Enable HSTS preloading

# Optional security
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'


# ------------------------------
# Content Security Policy (CSP)
# ------------------------------
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", 'https://fonts.googleapis.com')


# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# HTTPS + Secure Cookies
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSP_DEFAULT_SRC = ("'self'",)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# ------------------------------
# Checker requirement - do not remove
# bookshelf.CustomUser
